environment:

  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

build: off

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install --upgrade -vv setuptools"
  - "pip install --upgrade cython"
  - "pip install numpy"
  - "pip install freetype-py"
  - "pip install pypng"
  - "pip install --upgrade pywavelets"
  - "pip install pypiwin32"
  - "python setup.py install"
  - "git lfs install"
  - "git lfs pull"
  - "echo y | pip uninstall PyQt5"
  - "pip install PyQt5==5.9.2"
  - "git clone --depth=50 --branch=master https://github.com/populse/populse_db.git C:\\projects\\populse-db"
  - "cd C:\\projects\\populse-db"
  - "pip install -e .[postgres]"
  #- "pip install --force-reinstall lark-parser==0.6.7"
  - "cd .."
  - "git clone --depth=50 --branch=master https://github.com/populse/soma-base.git C:\\projects\\soma-base"
  - "cd populse-mia"
  - "SET PYTHONPATH=C:\\projects\\populse-mia\\python\\;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\soma-base\\python\\;%PYTHONPATH%"

test_script:
  - "python --version"
  - "python .\\python\\populse_mia\\test.py -v"

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
